services:
  training-deploy:
    build: .
    environment:
      - MODEL_NAME=hpc-feb-2023
    volumes:
      - ./norma/:/app
      - ./norma/weights/:/app/norma/weights
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
