services:
  training-deploy:
    build: .
    command: python -m norma train feb11at0906
    volumes:
      - ./norma/:/app
      # - ./norma/weights/:/app/norma/weights
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
