PROJECT_NAME : bagchal

DEV_MODE: true

ENGINE_IDENT: d4beab3f-9b3c-44df-ba62-d477fb33c67b

FIRST_SUPERUSER : test@test.com
FIRST_SUPERUSER_PASSWORD : test

UVICORN_HOST : localhost
UVICORN_WORKERS : 5
UVICORN_PORT : 8080

BACKEND_CORS_ORIGINS :
  - http://localhost:3001
  - http://localhost:3000
  - http://localhost

POSTGRES_SERVER : postgres
POSTGRES_USER : test
POSTGRES_PASSWORD : test
POSTGRES_DB : app

REDIS_HOST : localhost
REDIS_PORT : 6379
REDIS_PASSWORD : password 
